# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z2-6kgapOUWsKTgmgRr90Hq9tYXyPRT5
"""

import pandas as pd

df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/CardioGoodFitness-1.csv")

df.head()

df.head(10)

df.tail()

df.sample()

df.sample(10)

df.shape

df.dtypes

df.info()

df.isnull().sum()

df.describe()

df.describe(include="all")

